# Nombramiento del microservicio
spring.application.name=user-service

#Configuración BD en memeria H2(si, prueba inicial jaja)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#Conexión directa con la BD(en mi caso sql server v 21)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=airbnb_db;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=conexion123]

#creación bd apartir de user.java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#linea para que se puede leer el lenguaje SQL desde java
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#Habilitar consola en web
spring.h2.console.enabled=false